badges.endorsed=取得徽章：%s
badges.new=解锁徽章：%s
badges$badge.monsters_slain_1.title=新晋怪物猎人
badges$badge.monsters_slain_1.desc=在一局游戏中击败10个敌人
badges$badge.monsters_slain_2.title=进阶怪物猎人
badges$badge.monsters_slain_2.desc=在一局游戏中击败50个敌人
badges$badge.monsters_slain_3.title=专业怪物猎人
badges$badge.monsters_slain_3.desc=在一局游戏中击败100个敌人
badges$badge.monsters_slain_4.title=大师怪物猎人
badges$badge.monsters_slain_4.desc=在一局游戏中击败250个敌人
badges$badge.monsters_slain_5.title=宗师怪物猎人
badges$badge.monsters_slain_5.desc=在一局游戏中击败500个敌人
badges$badge.gold_collected_1.title=新晋财宝猎人
badges$badge.gold_collected_1.desc=在一局游戏中收集250金币
badges$badge.gold_collected_2.title=进阶财宝猎人
badges$badge.gold_collected_2.desc=在一局游戏中收集1000金币，以此解锁掠夺者
badges$badge.gold_collected_3.title=专业财宝猎人
badges$badge.gold_collected_3.desc=在一局游戏中收集2500金币
badges$badge.gold_collected_4.title=大师财宝猎人
badges$badge.gold_collected_4.desc=在一局游戏中收集7500金币
badges$badge.gold_collected_5.title=宗师财宝猎人
badges$badge.gold_collected_5.desc=在一局游戏中收集15000金币
badges$badge.level_reached_1.title=新晋冒险家
badges$badge.level_reached_1.desc=升到6级
badges$badge.level_reached_2.title=进阶冒险家
badges$badge.level_reached_2.desc=升到12级
badges$badge.level_reached_3.title=专业冒险家
badges$badge.level_reached_3.desc=升到18级
badges$badge.level_reached_4.title=大师冒险家
badges$badge.level_reached_4.desc=升到24级
badges$badge.level_reached_5.title=宗师冒险家
badges$badge.level_reached_5.desc=升到30级
badges$badge.all_weapons_identified.title=武器研究员
badges$badge.all_weapons_identified.desc=鉴定手册中所有类型的武器
badges$badge.all_armor_identified.title=护甲研究员
badges$badge.all_armor_identified.desc=鉴定手册中所有类型的护甲
badges$badge.all_wands_identified.title=法杖研究员
badges$badge.all_wands_identified.desc=鉴定手册中所有类型的法杖
badges$badge.all_rings_identified.title=戒指研究员
badges$badge.all_rings_identified.desc=鉴定手册中所有类型的戒指
badges$badge.all_artifacts_identified.title=神器研究员
badges$badge.all_artifacts_identified.desc=鉴定手册中所有类型的神器
badges$badge.all_potions_identified.title=药剂研究员
badges$badge.all_potions_identified.desc=鉴定手册中所有类型的药剂
badges$badge.all_scrolls_identified.title=卷轴研究员
badges$badge.all_scrolls_identified.desc=鉴定手册中所有类型的卷轴
badges$badge.all_items_identified.title=道具专家
badges$badge.all_items_identified.desc=鉴定手册中所有的物品
badges$badge.all_bags_bought.title=背包客
badges$badge.all_bags_bought.desc=完全扩充你的背包
badges$badge.death_from_fire.title=燃尽
badges$badge.death_from_fire.desc=死于火焰
badges$badge.death_from_poison.title=中毒
badges$badge.death_from_poison.desc=死于中毒
badges$badge.death_from_gas.title=窒息
badges$badge.death_from_gas.desc=死于毒气
badges$badge.death_from_hunger.title=饿毙
badges$badge.death_from_hunger.desc=死于饥饿
badges$badge.death_from_falling.title=跳进染缸！
badges$badge.death_from_falling.desc=死于坠落
badges$badge.death_from_enemy_magic.title=伏“法”
badges$badge.death_from_enemy_magic.desc=死于敌方法术攻击
badges$badge.death_from_friendly_magic.title=闹乌龙
badges$badge.death_from_friendly_magic.desc=死于你自己的魔法物品
badges$badge.death_from_sacrifice.title=上好祭品
badges$badge.death_from_sacrifice.desc=死在献祭之火中
badges$badge.death_from_grim_trap.title=致命失足
badges$badge.death_from_grim_trap.desc=死于即死陷阱或解离陷阱
badges$badge.death_in_devmode.title=朽木不可雕也
badges$badge.death_in_devmode.desc=在开发者模式下死亡
badges$badge.death_from_all.title=另类死亡爱好者
badges$badge.death_from_all.desc=解锁所有关于死因的徽章
badges$badge.boss_slain_1.title=粘液保洁员
badges$badge.boss_slain_1.desc=击败下水道尽头的Boss
badges$badge.boss_slain_2.title=典狱长
badges$badge.boss_slain_2.desc=击败监狱尽头的Boss
badges$badge.boss_slain_3.title=五金回收工
badges$badge.boss_slain_3.desc=击败洞穴尽头的Boss
badges$badge.boss_slain_4.title=弑王者
badges$badge.boss_slain_4.desc=击败矮人都城尽头的Boss
badges$badge.boss_slain_1_all_classes.title=千面手
badges$badge.boss_slain_1_all_classes.desc=以所有职业击败第一个Boss
badges$badge.boss_slain_3_all_subclasses.title=万事通
badges$badge.boss_slain_3_all_subclasses.desc=以所有专精后的职业击败第三个Boss
badges$badge.boss_slain_remains.title=复仇的滋味！
badges$badge.boss_slain_remains.desc=在持有死于某Boss的英雄的遗物的情况下击败该Boss
badges$badge.strength_attained_1.title=健身菜鸟
badges$badge.strength_attained_1.desc=基础力量达到12点
badges$badge.strength_attained_2.title=健身学徒
badges$badge.strength_attained_2.desc=基础力量达到14点
badges$badge.strength_attained_3.title=健身专家
badges$badge.strength_attained_3.desc=基础力量达到16点
badges$badge.strength_attained_4.title=健身大佬
badges$badge.strength_attained_4.desc=基础力量达到18点
badges$badge.strength_attained_5.title=健身巨佬
badges$badge.strength_attained_5.desc=基础力量达到20点
badges$badge.food_eaten_1.title=新晋美食家
badges$badge.food_eaten_1.desc=在一场游戏中进食10次
badges$badge.food_eaten_2.title=进阶美食家
badges$badge.food_eaten_2.desc=在一场游戏中进食20次
badges$badge.food_eaten_3.title=专业美食家
badges$badge.food_eaten_3.desc=在一场游戏中进食30次
badges$badge.food_eaten_4.title=大师美食家
badges$badge.food_eaten_4.desc=在一场游戏中进食40次
badges$badge.food_eaten_5.title=宗师美食家
badges$badge.food_eaten_5.desc=在一场游戏中进食50次
badges$badge.item_level_1.title=新晋附魔师
badges$badge.item_level_1.desc=获得一件等级大于等于3的物品
badges$badge.item_level_2.title=进阶附魔师
badges$badge.item_level_2.desc=获得一件等级大于等于6的物品
badges$badge.item_level_3.title=专业附魔师
badges$badge.item_level_3.desc=获得一件等级大于等于9的物品
badges$badge.item_level_4.title=大师附魔师
badges$badge.item_level_4.desc=获得一件等级大于等于12的物品
badges$badge.item_level_5.title=宗师附魔师
badges$badge.item_level_5.desc=获得一件等级大于等于15的物品
badges$badge.victory.title=通关！
badges$badge.victory.desc=获得Yendor护符
badges$badge.victory_all_classes.title=全能宗师
badges$badge.victory_all_classes.desc=以所有职业取得Yendor护符
badges$badge.mastery_combo.title=角斗士之怒
badges$badge.mastery_combo.desc=达成十连击
badges$badge.items_crafted_1.title=炼金学徒
badges$badge.items_crafted_1.desc=在一局游戏中通过炼金术合成3个物品
badges$badge.items_crafted_2.title=炼金熟手
badges$badge.items_crafted_2.desc=在一局游戏中通过炼金术合成8个物品
badges$badge.items_crafted_3.title=炼金专家
badges$badge.items_crafted_3.desc=在一局游戏中通过炼金术合成15个物品
badges$badge.items_crafted_4.title=炼金大师
badges$badge.items_crafted_4.desc=在一局游戏中通过炼金术合成24个物品
badges$badge.items_crafted_5.title=炼金宗师
badges$badge.items_crafted_5.desc=在一局游戏中通过炼金术合成35个物品
badges$badge.no_monsters_slain.title=和平主义者
badges$badge.no_monsters_slain.desc=在不击败任何敌人的情况下通过一个楼层
badges$badge.grim_weapon.title=死神来了
badges$badge.grim_weapon.desc=使用死神附魔击败一个敌人
badges$badge.piranhas.title=非主流垂钓
badges$badge.piranhas.desc=在一场游戏中杀死6只食人鱼
badges$badge.piranhas_2.title=专业钓鱼佬
badges$badge.piranhas_2.desc=在一场游戏中杀死10只食人鱼
badges$badge.boss_challenge_1.title=完杀无瑕
badges$badge.boss_challenge_1.desc=在未触发蓄力攻击与水面治疗的情况下，击败下水道区域Boss
badges$badge.boss_challenge_2.title=机巧无用
badges$badge.boss_challenge_2.desc=在不被任何机关陷阱击中的情况下，击败监狱区域Boss
badges$badge.boss_challenge_3.title=疾行无影
badges$badge.boss_challenge_3.desc=在过载期间完全规避所有攻击和伤害来源的情况下，击败洞穴区域Boss
badges$badge.boss_challenge_4.title=掣君无刃
badges$badge.boss_challenge_4.desc=在不使用武器、戒指、法杖或攻击性法术进行对其直接攻击的情况下，击败都城区域Boss
badges$badge.boss_challenge_5.title=制霸无敌
badges$badge.boss_challenge_5.desc=在开启“绝命头目”挑战、且所有恶魔血巢存活的情况下击败最终Boss
badges$badge.games_played_1.title=新晋地牢人
badges$badge.games_played_1.desc=进行10场游戏或通关1场游戏
badges$badge.games_played_2.title=进阶地牢人
badges$badge.games_played_2.desc=进行25场游戏或通关3场游戏
badges$badge.games_played_3.title=资深地牢人
badges$badge.games_played_3.desc=进行50场游戏或通关5场游戏
badges$badge.games_played_4.title=大师地牢人
badges$badge.games_played_4.desc=进行200场游戏或通关10场游戏
badges$badge.games_played_5.title=究极地牢人
badges$badge.games_played_5.desc=进行1000场游戏或通关25场游戏
badges$badge.high_score_1.title=新晋角逐者
badges$badge.high_score_1.desc=在结束游戏时达到5000分或更高
badges$badge.high_score_2.title=进阶角逐者
badges$badge.high_score_2.desc=在结束游戏时达到25,000分或更高
badges$badge.high_score_3.title=专业角逐者
badges$badge.high_score_3.desc=在结束游戏时达到100,000分或更高
badges$badge.high_score_4.title=大师角逐者
badges$badge.high_score_4.desc=在结束游戏时达到250,000分或更高
badges$badge.high_score_5.title=宗师角逐者
badges$badge.high_score_5.desc=在结束游戏时达到1,000,000分或更高
badges$badge.researcher_1.title=新晋调查员
badges$badge.researcher_1.desc=在日志中解锁40个图鉴条目
badges$badge.researcher_2.title=进阶调查员
badges$badge.researcher_2.desc=在日志中解锁80个图鉴条目
badges$badge.researcher_3.title=专业调查员
badges$badge.researcher_3.desc=在日志中解锁160个图鉴条目
badges$badge.researcher_4.title=高级调查员
badges$badge.researcher_4.desc=在日志中解锁320个图鉴条目
badges$badge.researcher_5.title=特级调查员
badges$badge.researcher_5.desc=在日志中解锁640个图鉴条目
badges$badge.catalog_one_equipment.title=百般武艺
badges$badge.catalog_one_equipment.desc=在日志中解锁每种装备的任一图鉴条目
badges$badge.catalog_potions_scrolls.title=万物通识
badges$badge.catalog_potions_scrolls.desc=在一局游戏中鉴定每种药剂和卷轴
badges$badge.all_rare_enemies.title=魔兽世界
badges$badge.all_rare_enemies.desc=在日志中解锁十个稀有敌人的图鉴条目
badges$badge.rodney.title=泯然众人
badges$badge.rodney.desc=在背景故事的终幕中知晓矮人国王的真名
badges$badge.happy_end.title=幸福结局
badges$badge.happy_end.desc=将Yendor护符带出地牢
badges$badge.happy_end_remains.title=现在...你也...
badges$badge.happy_end_remains.desc=将一位英雄的遗物带回地表
badges$badge.champion_1.title=青铜斗士
badges$badge.champion_1.desc=在启用至少一个挑战（除测试时间）的情况下通关
badges$badge.champion_2.title=白银斗士
badges$badge.champion_2.desc=在启用至少三个挑战（除测试时间）的情况下通关
badges$badge.champion_3.title=黄金斗士
badges$badge.champion_3.desc=在启用至少六个挑战（除测试时间）的情况下通关
badges$badge.champion_4.title=铂金斗士
badges$badge.champion_4.desc=在启用至少十个挑战（除测试时间）的情况下通关
badges$badge.champion_5.title=钻石斗士
badges$badge.champion_5.desc=在启用十五个挑战（除测试时间）的情况下通关
badges$badge.unlock_mage.title=解锁法师！
badges$badge.unlock_mage.desc=使用一张升级卷轴以解锁法师
badges$badge.unlock_rogue.title=解锁盗贼！
badges$badge.unlock_rogue.desc=在一场游戏中进行十次伏击以解锁盗贼
badges$badge.unlock_huntress.title=解锁女猎手！
badges$badge.unlock_huntress.desc=在一场游戏中使用投掷武器命中十次敌人以解锁女猎手
badges$badge.unlock_duelist.title=解锁决斗家！
badges$badge.unlock_duelist.desc=不受力量惩罚地装备一个2阶或更高阶的武器以解锁决斗家
badges$badge.unlock_cleric.title=解锁牧师！
badges$badge.unlock_cleric.desc=完全净化任何一件被诅咒装备的诅咒以解锁牧师
badges$badge.unlock_explorer.title=解锁探险家！
badges$badge.unlock_explorer.desc=在水中熄灭身上的火焰或洗去淤泥以解锁探险家
badges$badge.unlock_wraith.title=解锁怨魂！
badges$badge.unlock_wraith.desc=将生命值降到最大值的二成或更低以解锁怨魂
badges$badge.unlock_engineer.title=解锁工程师！
badges$badge.unlock_engineer.desc=在一场游戏中触发五次陷阱以解锁工程师
badges$badge.enemy_hazards.title=安全隐患
badges$badge.enemy_hazards.desc=在一局游戏中通过特殊地形(陷阱、植物或深渊)击败10个敌人
badges$badge.many_buffs.title=狂乱的鸡尾酒
badges$badge.many_buffs.desc=同时获有至少10种增益/减益图标
badges$badge.pacifist_ascent.title=和平凯旋
badges$badge.pacifist_ascent.desc=将其诅咒未曾减弱的Yendor护符带出地牢
badges$badge.taking_the_mick.title=适才相戏耳
badges$badge.taking_the_mick.desc=以一把至少20级的镐子对最终boss打出致命一击
badges$badge.ripper_human.title=人类撕裂者
badges$badge.ripper_human.desc=以一把撕裂者骨爪杀死一只恶魔撕裂者
badges$badge.refutation.title=现在谁才是巨蝎？
badges$badge.refutation.desc=在一只巨蝎身上插上至少5个巨蝎尖刺
badges$badge.blasphemy.title=渎神
badges$badge.blasphemy.desc=将筝型盾卖给店主\n\n“你给我等着！”——迅>ˍ<
badges$badge.victory_random.title=混沌中的常量
badges$badge.victory_random.desc=在英雄、天赋、专精与护甲技能均为随机的条件下获得Yendor护符

challenges.no_food=缩餐节食
challenges.no_food_desc=食物本就稀缺，但你还需要注意节食！\n\n_-_使用各类食物与丰饶之角的饱腹效果为原本的三分之一\n_-_其他恢复饥饿的机制不受影响
challenges.no_armor=信念护体
challenges.no_armor_desc=如今护甲已难堪大用，你只能相信你自己的肉身了！\n\n_-_布甲之外所有护甲的基本防御力降低\n_-_所有护甲升级提供的防御力成长大幅降低\n_-_灵壤守卫的防御力大幅降低
challenges.no_healing=恐药异症
challenges.no_healing_desc=治疗药剂真是种好东西，可惜你对它过敏！\n\n_-_治疗药剂、以治疗药剂为原料炼制的道具与阳春果将无法治愈英雄，反而会使英雄中毒\n_-_紊乱魔药不会随机到治愈英雄或使英雄中毒的效果\n_-_这些道具对其他单位依然发挥正常效果。
challenges.no_herbalism=荒芜之地
challenges.no_herbalism_desc=这个晦气的地牢里连干净的水都没有了...\n\n_-_移除露珠\n_-_移除所有特殊植物\n_-_高草依然会掉落种子，但种子不会生根发芽
challenges.swarm_intelligence=集群智能
challenges.swarm_intelligence_desc=要小心了，地牢里的怪物们也在学习进步！\n\n_-_当你被敌人发现时，附近的其他敌人也会被吸引到那里。
challenges.darkness=没入黑暗
challenges.darkness_desc=地牢毕竟是在地下嘛！\n\n_-_正常视野范围显著缩小\n_-_每层都会出现一根火把\n_-_其他光源有效性降至1/5
challenges.no_scrolls=禁忌咒文
challenges.no_scrolls_desc=一种卷轴会变得更稀有。不幸的是，总是最有用的那一种。\n\n_-_移除地牢中半数的升级卷轴
challenges.champion_enemies=精英强敌
challenges.champion_enemies_desc=道高一尺魔高一丈，变强可不是你的特权！\n\n_-_普通敌人刷出时有1/8的概率拥有特殊的精英属性\n_-_精英敌人刷出时会立即醒来\n_-_有精英敌人出现时英雄会感知到\n_-_精英敌人免疫腐化效果\n\n精英敌人有十三种：\n_烈焰(橙色)：_近战伤害+25%且带有点燃效果，死亡时引燃周围，无法点燃含水地块\n_索敌(紫色)：_近战伤害+25%，近战范围+3\n_敌法(绿色)：_受到伤害-50%，拥有魔法免疫\n_巨型(亮蓝色)：_受到伤害-80%，近战范围+1，无法进入门与过道\n_天佑(黄色)：_精准与闪避x4\n_成长(红色)：_精准、闪避、攻击伤害与有效生命值+20%，且每过4回合会再增长1%\n_玉碎(白色)：_近战伤害 x3，受到伤害 x5，精准 x10，闪避 x0\n_狂战(粉色)：_近战伤害随失去生命值而上升，最高 +60%\n_血饮(深红色)：_近战伤害 +25% 且恢复 12.5% 已损生命值\n_冰霜(深蓝色)：_近战伤害 +25% 且带有冻伤效果，死亡时霜冻周围水面并冻结水上敌人\n_腐蚀(青色)：_近战伤害 +25% 且带有腐蚀效果，死亡时腐蚀非水上敌人\n_转移(灰色)：_近战伤害 +25% 且攻击时传送自身\n_电击(深黄色)：_近战伤害 +25% 且带有麻痹效果，死亡时在身旁水面放电
challenges.stronger_bosses=绝命头目
challenges.stronger_bosses_desc=这项挑战会让所有Boss都更具挑战性！\n\n_粘咕：_生命值+20%\n_-_持续处于水中时，生命回复量递增，最高至每回合3点\n_-_爆发攻击蓄力时间由2回合缩短至1回合\n_天狗：_生命+25%\n_-_第一阶段：陷阱更加致命\n_-_第二阶段：技能频率更高\n_DM-300：_生命+33%\n_-_能量塔更坚固，并且需要击毁3座\n_-_技能频率更高，威力也更强大\n_-_地表导线数量为原先的两倍\n_矮人国王：_生命+50%\n_-_所有阶段中都会召唤更多强力随从\n_-_第一阶段：更高的技能与召唤频率\n_-_第二阶段：每轮额外召唤两名随从\n_-_第三阶段：生命值+100%，进一步提高召唤频率\n_Yog-Dzewa：_\n_-_同时召唤两个古神之拳！\n_-_激光攻击伤害+60%\n_-_召唤更强大的随从
challenges.x_u_ns_power=测试时间
challenges.x_u_ns_power_desc=你现在可以像开发者一样，利用强大的开发工具做任何你想做的事！然而，开发者的力量不是白给的……\n\n_-_始于调试卷轴、纯金箭头、完美护盾、神秘镐子、面具、王冠、所有扩展包裹、65520 张升级卷轴、10 瓶力量药剂、29 瓶经验药剂、+50 能量之戒、拟态之刃与 +210 札甲\n_-_你可以依靠点击图鉴获得任意物品、附魔与刻印，召唤任意敌人，建造任意陷阱，种植任意植物或是发现任意日志\n_-_你还会获得一些因为种种原因没有加入游戏的物品\n\n_-_结算时分数为 _0 分_，且不计入排行榜\n_-_无法取得除图鉴类或“朽木不可雕也”以外的徽章\n_-_护符不会在 26 层生成
challenges.heavy_burden=负重前行
challenges.heavy_burden_desc=你感觉包里的物品沉重不堪……\n\n_-_所有物品拥有重量值\n_-_包内物品总重量值超过英雄力量值时，英雄的精准、闪避和移速每超出 0.01 点减少 0.25%，移速不会因此减到比 0.1 格/回合更低，精准与闪避可以减到低于 0\n_-_英雄在包内物品即将或已经超重时获得提示\n_-_装备着的与拓展背包中的物品不计重量\n\n_-_各类物品的重量值：\n近战武器与护甲：力量需求的 10%\n投掷武器与灵能弓：力量需求的 5%\n神器、戒指、法杖与饰品：0.3\n拓展背包：0.5\n液金：0.03\n单次产量大于 1 的魔药与法术结晶：0.1/产量\n其他物品：0.1
challenges.crazy_loot=疯狂掠夺
challenges.crazy_loot_desc=贪婪之心人人皆有，掠夺可不是你的特权！\n\n_-_敌人在游荡时会主动捡起地上的最多一件物品并携带之，这些物品在敌人死亡时掉落\n_-_携带了捡起的物品的敌人的原有战利品掉落率 -50%\n_-_英雄可以看见敌人是否携带了物品\n_-_疯狂小偷与土匪们不屑于弯腰，因为他们现在可以从你包里偷走带有升级的物品
challenges.exercises=强身健体
challenges.exercises_desc=现在你不仅没有时间通过训练来掌握新武器和护甲，也没有蛮力：你只能赶鸭子上架了……\n\n_-_饮用力量药剂依次使英雄获得长时间虚弱、恍惚和易伤\n_-_武器和护甲随升级降低的力量需求减少\n_-_所有投掷武器的力量需求 +1，镐子的力量需求 -1
challenges.no_return=无归旅途
challenges.no_return_desc=显然地牢的建筑质量不是很好，因为脚下摇晃着的地板告诉你它正在逐渐坍塌！\n\n_-_如果不做任何干预，地牢将在 12000 回合内完全崩塌，每 500 回合一层；第 25 和 26 层不会坍塌\n_-_楼层坍塌后，英雄将无法返回；如果楼层坍塌时英雄位于此层，则在头目层或任务子层英雄每回合受到等同于 10% 最大生命值的伤害，反之直接摔到下一层\n_-_临近崩塌时，地牢将剧烈震荡，英雄获得文字提示\n\n_-_炼制或在商店购买地牢支架并使用，对铁匠任务头目或小恶魔任务头目造成伤害可以减缓崩塌的速度\n_-_护符诡咒以 3 倍速率累积，但返程期间进入已坍塌楼层或第 20 层将直接结束游戏；如此结束游戏时每向上走一层，结算时胜利倍率 +0.1 倍，最高计算 5 层
challenges.blunted_blade=刀钝刃卷
challenges.blunted_blade_desc=似乎负责铸造地牢中武器的工匠们喝多了：你现在在地牢里看到的只有一堆垃圾！\n\n_-_所有物理武器生成时有 50% 概率被替换为低一阶的另一把；因此，一阶武器可能在地牢中生成\n_-_悲伤幽灵和巨魔铁匠的奖励、商店和嬗变不受影响
challenges.mana_exhaustion=法力耗散
challenges.mana_exhaustion_desc=你感觉每次施法时的精神集中都使你越发疲惫……\n\n_-_每次消耗法杖中的充能都会使英雄进入或叠加法力耗散状态\n_-_法力耗散使法杖暂停充能，叠加到 12 回合时使法杖降级，24 回合时使施法耗时增加，36 回合时使英雄在施法时受到伤害\n_-_储能护盾不会触发该挑战

rankings$record.something=在黑暗中被击杀
rankings$record.won=获得Yendor护符
rankings$record.ascended=成功携带护符回到地面！
rankings$record.ascended_collapse=借助护符逃脱崩塌的地牢